#!/usr/bin/env bash
set -e

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

cleanup() {
  echo ""
  echo "Shutting down all services..."
  kill "$PAYMENTS_PID" "$GATEWAY_PID" 2>/dev/null || true
  wait "$PAYMENTS_PID" "$GATEWAY_PID" 2>/dev/null || true
  echo "Done."
}
trap cleanup SIGINT SIGTERM

echo "Starting upstream services..."
node "$ROOT/examples/circuit-breaker/upstream-payments.js" &
PAYMENTS_PID=$!

echo "Starting gateway..."
cp "$ROOT/examples/circuit-breaker/.env" "$ROOT/.env"
cd "$ROOT" && pnpm dev &
GATEWAY_PID=$!

sleep 2

echo ""
echo "  Services"
echo "  ──────────────────────────────────────────────────────────"
echo "  Gateway (public)   →  http://localhost:3000"
echo "  Health check       →  http://localhost:3000/health"
echo "  Payments API       →  http://localhost:3000/payments  ← circuit breaker enabled"
echo ""
echo "  Payments admin     →  http://localhost:4066           ← not exposed through gateway"
echo "  ──────────────────────────────────────────────────────────"
echo ""
echo "  Circuit breaker config (routes.json)"
echo "    threshold        3 failures   → circuit opens"
echo "    timeout          10 s         → stays open before probing"
echo "    successThreshold 1 success    → probe closes the circuit"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " W A L K T H R O U G H"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "── Step 1 · Normal operation (circuit CLOSED) ─────────────────"
echo ""
echo "  # List payments — upstream is healthy, requests go straight through"
echo "  curl -s http://localhost:3000/payments | jq"
echo ""
echo "  # Create a payment"
echo "  curl -s -X POST http://localhost:3000/payments \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"userId\":3,\"amount\":59.99}' | jq"
echo ""
echo "── Step 2 · Degrade the upstream ─────────────────────────────"
echo ""
echo "  # Tell the payments service to start returning 500s"
echo "  curl -s -X POST http://localhost:4066/mode \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"mode\":\"failing\"}' | jq"
echo ""
echo "── Step 3 · Trigger the circuit breaker (threshold = 3) ───────"
echo ""
echo "  # Each of these returns 500 from the upstream — the gateway"
echo "  # tracks them. On the 3rd failure the circuit opens."
echo "  curl -s http://localhost:3000/payments | jq  # failure 1"
echo "  curl -s http://localhost:3000/payments | jq  # failure 2"
echo "  curl -s http://localhost:3000/payments | jq  # failure 3 → circuit OPEN"
echo ""
echo "── Step 4 · Observe the OPEN circuit ─────────────────────────"
echo ""
echo "  # These requests never reach the upstream — the gateway short-circuits"
echo "  # and returns 503 with a Retry-After header immediately."
echo "  curl -si http://localhost:3000/payments | head -20"
echo ""
echo "  # The upstream receives nothing (watch its stdout to confirm)"
echo ""
echo "── Step 5 · Restore the upstream ─────────────────────────────"
echo ""
echo "  # Signal the payments service to recover"
echo "  curl -s -X POST http://localhost:4066/mode \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"mode\":\"healthy\"}' | jq"
echo ""
echo "── Step 6 · Wait for the timeout and observe the probe ────────"
echo ""
echo "  # The circuit stays OPEN for 10 s, then transitions to HALF_OPEN."
echo "  # The first request after the timeout is forwarded as a probe."
echo "  # Watch the gateway log — you will see the state transition logged."
echo ""
echo "  sleep 11 && curl -s http://localhost:3000/payments | jq"
echo ""
echo "  # The probe succeeds → circuit closes → subsequent requests are proxied normally."
echo "  curl -s http://localhost:3000/payments | jq"
echo ""
echo "── Tips ────────────────────────────────────────────────────────"
echo ""
echo "  Check current upstream mode at any time:"
echo "    curl -s http://localhost:4066/status | jq"
echo ""
echo "  Watch gateway logs for state transition messages:"
echo "    circuit breaker opened   → threshold reached"
echo "    circuit breaker half-open → timeout elapsed, sending probe"
echo "    circuit breaker closed   → probe succeeded, service recovered"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  Press Ctrl+C to stop all services."
echo ""

wait "$GATEWAY_PID"
