#!/usr/bin/env bash
set -euo pipefail

echo ""
echo "  Services"
echo "  Gateway (public)   →  http://localhost:3000"
echo "  Health check       →  http://localhost:3000/health"
echo "  Metrics endpoint   →  http://localhost:3000/metrics   ← Prometheus"
echo "  Orders API         →  http://localhost:3000/orders    ← cache + metrics"
echo ""
echo "  Orders admin       →  http://localhost:4031           ← not exposed through gateway"
echo ""
echo "  Metrics exposed"
echo "    gateway_requests_total{route,method,status_code}"
echo "    gateway_request_duration_seconds{route,method}"
echo "    gateway_upstream_errors_total{route,error_type}"
echo "    gateway_cache_hits_total{route}"
echo ""
echo " W A L K T H R O U G H"
echo ""
echo ""
echo "  curl -s http://localhost:3000/orders | jq"
echo "  curl -s http://localhost:3000/orders | jq"
echo "  curl -s http://localhost:3000/orders/1 | jq"
echo ""
echo ""
echo "  # Full Prometheus text output"
echo "  curl -s http://localhost:3000/metrics"
echo ""
echo "  # Filter to gateway-specific metrics only"
echo "  curl -s http://localhost:3000/metrics | grep '^gateway_'"
echo ""
echo ""
echo "  # The orders route has cache enabled (TTL 10 s)."
echo "  # First GET is a MISS, subsequent GETs are HITs."
echo "  curl -si http://localhost:3000/orders | grep X-Cache"
echo "  curl -si http://localhost:3000/orders | grep X-Cache"
echo ""
echo "  # gateway_cache_hits_total should now be 1"
echo "  curl -s http://localhost:3000/metrics | grep gateway_cache_hits_total"
echo ""
echo ""
echo "  # Switch orders service to failing mode"
echo "  curl -s -X POST http://localhost:4031/mode \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"mode\":\"failing\"}' | jq"
echo ""
echo "  # Wait for cache to expire, then make a request that hits the upstream"
echo "  sleep 11 && curl -s http://localhost:3000/orders | jq"
echo ""
echo "  # gateway_upstream_errors_total should increment"
echo "  curl -s http://localhost:3000/metrics | grep gateway_upstream_errors_total"
echo ""
echo ""
echo "  curl -s -X POST http://localhost:4031/mode \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"mode\":\"healthy\"}' | jq"
echo ""
echo "  curl -s http://localhost:3000/metrics | grep '^gateway_'"
echo ""
echo ""
echo "  To scrape metrics with Prometheus, add this to your prometheus.yml:"
echo "    scrape_configs:"
echo "      - job_name: api-gateway"
echo "        static_configs:"
echo "          - targets: ['localhost:3000']"
echo "        metrics_path: /metrics"
echo ""
echo ""
echo "  Press Ctrl+C to stop all services."
echo ""
